version: '3'
services:
  db:
    image: mysql:8.0.32
    container_name: beMobileDB
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=beMobileDB
    restart: 'always'